### ISSUE TITLE
Traceback (most recent call last):   File "boundary.py", line 294, in <module>     selected_animals = select_animal(animals, fitness)   File "boundary.py", line 240, in select_animal     idx = np.random.choice(np.arange(N), size=N, replace=True, p=(fitness / (np.sum(fitness) + 1e-8)))   File "mtrand.pyx", line 958, in numpy.random.mtrand.RandomState.choice ValueError: probabilities do not sum to 1

### ISSUE THREAD

**Issue by windloveyou** [xuxuxuxuxuxjh/LB-UNet#3]
When i run the boundary.py to use the isic2017 dataset(from the EGE-UNet), it goes wrong. Luckily, the isic2018 goes successfully!
"""
Traceback (most recent call last):
  File "boundary.py", line 294, in <module>
    selected_animals = select_animal(animals, fitness)
  File "boundary.py", line 240, in select_animal
    idx = np.random.choice(np.arange(N), size=N, replace=True, p=(fitness / (np.sum(fitness) + 1e-8)))
  File "mtrand.pyx", line 958, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
"""
Are there any problems with the boundary.py ?
If it is convenient for you, can you directly provide me with the boundary picture obtained after successful operation?
My email address is the windlovey@gmail.com.
Please help me, thank you!!!

**Comment by xuxuxuxuxuxjh** [comment]
This situation makes me very confused, but I have already sent you the boundary maps of isic2017.
